apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: test-exact-1
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - 'foo'
    routes:
      - matcher:
          exact: /
        routeAction:
          single:
            upstream:
              name: json-upstream
              namespace: gloo-system
